---
title: "Email Report"
author: "Justin Wininger"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, dpi = 300)
remove(list = ls())
library(readxl)
library(tidyverse)
library(lubridate)
library(hrbrthemes)
library(viridis)
library(mosaic)

emails <- read_excel("PGI master.xlsx")


emails <- emails %>%
  mutate(`Open Rate` = `Open Rate` * 100)

emails <- emails %>%
  mutate(`Click Rate` = `Click Rate` * 100)
```

```{r, data}
emails$Day <- as.Date(emails$`Sent Date`)
emails$Day <- weekdays(emails$Day)
day_order <- c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday")
emails$Day <- factor(emails$Day, levels = day_order, ordered = TRUE)


emails <- emails %>% filter(`Total Recipients` > 20 & Opens > 10)

emails$Covid <- ifelse(emails$`Sent Date` < as.Date("2020-03-01"), "Pre-COVID", "Post-COVID")

covid_order <- c("Pre-COVID", "Post-COVID")
emails$Covid <- factor(emails$Covid, levels = covid_order, ordered = TRUE)

emailsMF <- emails %>% filter(Day != 'Sunday')
emailsS <- emails %>% filter(Day == 'Sunday')
emailsW <- emails %>% filter(Day == 'Wednesday')

countsMF <- emailsMF %>% 
  group_by(Day) %>%
  tally()

counts <- emails %>% 
  group_by(Day) %>%
  tally()

emails$Size <- ifelse(emails$`Total Recipients` >= 2500, "Large", "Small")
```

# Introduction

This project analyzes several statistics of 645 email campaigns sent out by clients of Endowment Development Services since 2010.

```{r, warning = FALSE, message = FALSE}
emailsBC <- subset(emailsMF, Covid == "Pre-covid")
emailsAC <- subset(emailsMF, Covid == "Post-covid")

countsMF2 <- emailsMF %>% 
  group_by(Day, Covid) %>%
  tally()
```

```{r message = FALSE, warning = FALSE}
emails <- emails %>% mutate(`Subject Length` = nchar(Subject))

SL <- lm(`Open Rate` ~ `Subject Length`, data = emails)

sSL <- summary(SL)

sSLo <- sSL[["coefficients"]]
```

```{r}
has_punctuation <- function(text) {
  grepl("[[:punct:]]", text)
}

# Add a new column 'contains_punctuation' based on the presence of punctuation
emails <- emails %>%
  mutate(Punctuation = ifelse(has_punctuation(Subject), "Yes", "No"))

counts2 <- emails %>% 
  group_by(Punctuation) %>%
  tally()
```

```{r}
# Function to check for specific punctuation marks
has_period <- function(text) {
  grepl("\\.", text)
}

has_colon <- function(text) {
  grepl(":", text)
}

has_exclamation <- function(text) {
  grepl("!", text)
}

has_question <- function(text) {
  grepl("\\?", text)
}

has_comma <- function(text) {
  grepl("\\,", text)
}

has_hyphen <- function(text) {
  grepl("\\-", text)
}

has_ampersand <- function(text) {
  grepl("\\&", text)
}

has_quote <- function(text) {
  grepl('\\"', text)
}

has_em <- function(text) {
  grepl('\\—', text)
}

has_em2 <- function(text) {
  grepl('\\–', text)
}

has_slash <- function(text) {
  grepl('\\/', text)
}

# Add new columns for specific punctuation marks
emails <- emails %>%
  mutate(
    Period = ifelse(has_period(Subject), "Yes", "No"),
    Colon = ifelse(has_colon(Subject), "Yes", "No"),
    ExclamationPoint = ifelse(has_exclamation(Subject), "Yes", "No"),
    QuestionMark = ifelse(has_question(Subject), "Yes", "No"),
    Comma = ifelse(has_comma(Subject), "Yes", "No"),
    Hyphen = ifelse(has_hyphen(Subject), "Yes", "No"),
    Ampersand = ifelse(has_ampersand(Subject), "Yes", "No"),
    Quote = ifelse(has_quote(Subject), "Yes", "No"),
    Em = ifelse(has_em(Subject), "Yes", "No"),
    Em2 = ifelse(has_em2(Subject), "Yes", "No"),
    Slash = ifelse(has_slash(Subject), "Yes", "No")
  )
```

```{r}
haveP <- emails %>%
  filter(Period == "Yes") %>%
  mutate(Punc = "Period")
haveC <- emails %>%
  filter(Colon == "Yes") %>%
  mutate(Punc = "Colon")
haveE <- emails %>%
  filter(ExclamationPoint == "Yes")%>%
  mutate(Punc = "Exclamation\nPoint")
haveQ <- emails %>%
  filter(QuestionMark == "Yes")%>%
  mutate(Punc = "Question\nMark")
haveN <- emails %>%
  filter(Punctuation == "No")%>%
  mutate(Punc = "None")
haveCom <- emails %>%
  filter(Comma == 'Yes')%>%
  mutate(Punc = 'Comma')
haveD <- emails %>%
  filter(Hyphen == 'Yes' | Em == 'Yes' | Em2 == 'Yes')%>%
  mutate(Punc = 'Dash')
haveAmp <- emails %>%
  filter(Ampersand == 'Yes')%>%
  mutate(Punc = 'Ampersand')
haveQuo <- emails %>%
  filter(Quote == 'Yes')%>%
  mutate(Punc = 'Quotes')
haveSlash <- emails %>%
  filter(Slash == 'Yes')%>%
  mutate(Punc = 'Slash')


tmp <- emails %>% filter(Punctuation == 'Yes' & (Hyphen == 'Yes' | Em == 'Yes' | Em2 == 'Yes'))

havePunc <- do.call("rbind", list(haveP, haveC, haveE, haveQ, haveN, haveCom, haveD, haveAmp, haveQuo, haveSlash))

havePunc <- havePunc %>% 
  group_by(Punc) %>%
  filter(n() >= 15)

counts7 <- havePunc %>% 
  group_by(Punc) %>%
  tally()
```

```{r, warning = FALSE, message = FALSE}
analyze_last_char <- function(text) {
  last_char <- substr(text, nchar(text), nchar(text))
  if (last_char == ".") {
    return("Period")
  } else if (last_char == "!") {
    return("Exclamation")
  } else if (last_char == "?") {
    return("Question")
  } else if (last_char == ":") {
    return("Colon")
  } else if (last_char == "&") {
    return("Ampersand")
  } else if (last_char == ",") {
    return("Comma")
  } else if (last_char == "/") {
    return("Slash")
  } else if (last_char == '"') {
    return("Quotes")
  } else if (last_char == "-" | last_char == "—" | last_char == "–") {
    return("Dash")
  } else {
    return("No Punctuation")
  }
}

# Create new column with analysis of last character
emails$lastChar <- sapply(emails$Subject, analyze_last_char)

emailsLC <- emails %>% 
  filter(lastChar == 'Period' | lastChar == 'No Punctuation') 

counts6 <- emails %>% 
  group_by(lastChar) %>%
  tally()

counts3 <- emailsLC %>% 
  group_by(lastChar) %>%
  tally()
```

```{r}
noPunc <- emails %>% filter(Punctuation == "No")
noPunc <- noPunc %>%
  mutate (Source = "No Punctuation")
emailsNP <- emailsLC %>% 
  filter(lastChar == 'No Punctuation') %>%
  mutate (Source = "No Ending Punctuation")
emailsP <- emailsLC %>% 
  filter(lastChar == 'Period')%>%
  mutate (Source = "Ending Period") 
tmp <- rbind(emailsNP, emailsP)
both <- rbind(tmp, noPunc)

countsBoth <- both %>% 
  group_by(Source) %>%
  tally()

both2 <- rbind(emailsP, noPunc)

countsBoth2 <- both2 %>% 
  group_by(Source) %>%
  tally()
```

```{r}
countsSize <- emails %>% 
  group_by(Size) %>%
  tally()

emails <- emails %>%
  group_by(Client, Subject) %>%
  mutate(Duplicate = if_else(n_distinct(`Sent Date`) > 1, "Yes", "No")) %>%
  ungroup()

countsDup <- emails %>% 
  group_by(Duplicate) %>%
  tally()
```

```{r}
analyze_keywords <- function(data, subject_col, keywords) {
  emails <- emails %>%
    mutate(across(all_of(subject_col), tolower, .names = "lower_{col}"))
  
  for (keyword_group in keywords) {
    # Split the keywords if there are synonyms
    keyword_synonyms <- unlist(strsplit(keyword_group, "/"))
    base_keyword <- keyword_synonyms[1]
    
    # Create a new column name
    new_col_name <- paste0("have", base_keyword)
    
    # Check if any of the synonyms are in the subject column
    emails[[new_col_name]] <- ifelse(grepl(paste(keyword_synonyms, collapse = "|"), emails[[paste0("lower_", subject_col)]]), "Yes", "No")
  }
  
  # Check for numbers 1-10 in both numeric and written form
  numbers_written <- c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten")
  numbers_numeric <- as.character(1:10)
  all_numbers <- c(numbers_written, numbers_numeric)
  emails[["haveNumber"]] <- ifelse(grepl(paste(all_numbers, collapse = "|"), emails[[paste0("lower_", subject_col)]]), "Yes", "No")
  
  # Remove the temporary lowercase subject column
  emails <- emails %>%
    select(-starts_with("lower_"))
  
  return(emails)
}

# Example usage
# Assuming `df` is your dataset and `Subject` is the column to analyze
keywords <- c("gift/gifts", "legacy/legacies", "easy/smart/simple", "you/your/yours", 
              "impact/effect/affect", "option/options", "meaningful", "wise", 
              "support", "year-end", "give", "reward/rewarding", "will", 
              "support", "tax/taxes", "us/we", "help", "plan/planning")

# Applying the function to the dataset
emails <- analyze_keywords(emails, "Subject", keywords)
```

```{r}
haveGift <- emails %>%
  filter(havegift == "Yes") %>%
  mutate(Keyword = "Gift(s)")
haveLegacy <- emails %>%
  filter(havelegacy == "Yes") %>%
  mutate(Keyword = "Legacy(ies)")
haveEasy <- emails %>%
  filter(haveeasy == "Yes")%>%
  mutate(Keyword = "Easy / Smart / Simple")
haveYou <- emails %>%
  filter(haveyou == "Yes")%>%
  mutate(Keyword = "You / Your / Yours")
haveImpact <- emails %>%
  filter(haveimpact == "Yes")%>%
  mutate(Keyword = "Impact / Effect")
haveOption <- emails %>%
  filter(haveoption == 'Yes')%>%
  mutate(Keyword = 'Option(s)')
haveMeaningful <- emails %>%
  filter(havemeaningful == 'Yes')%>%
  mutate(Keyword = 'Meaningful')
haveWise <- emails %>%
  filter(havewise == 'Yes')%>%
  mutate(Keyword = 'Wise')
haveSupport <- emails %>%
  filter(havesupport == 'Yes')%>%
  mutate(Keyword = 'Support')
haveYearEnd <- emails %>%
  filter(`haveyear-end` == 'Yes')%>%
  mutate(Keyword = 'Year-End')
haveNumber <- emails %>%
  filter(haveNumber == "Yes") %>%
  mutate(Keyword = "A Number")
haveGive <- emails %>%
  filter(havegive == "Yes") %>%
  mutate(Keyword = "Give")
haveReward <- emails %>%
  filter(havereward == "Yes")%>%
  mutate(Keyword = "Reward(ing)")
haveWill <- emails %>%
  filter(havewill == "Yes")%>%
  mutate(Keyword = "Will")
haveTax <- emails %>%
  filter(havetax == "Yes")%>%
  mutate(Keyword = "Tax(es)")
haveUs <- emails %>%
  filter(haveus == 'Yes')%>%
  mutate(Keyword = 'Us / We')
haveHelp <- emails %>%
  filter(havehelp == 'Yes')%>%
  mutate(Keyword = 'Help')
havePlan <- emails %>%
  filter(haveplan == 'Yes')%>%
  mutate(Keyword = 'Plan(ning)')

keywords <- do.call("rbind", list(haveGift, haveLegacy, haveEasy, haveYou, haveImpact, haveOption, haveMeaningful, haveWise, haveSupport, haveYearEnd, haveNumber, haveGive, haveReward, haveWill, haveTax, haveUs, haveHelp, havePlan))

countsKeywords <- keywords %>% 
  group_by(Keyword) %>%
  tally()
```

```{r plots, warning = FALSE, message = F}
ggplot(data=emailsMF, mapping=aes(x=Day, y=`Open Rate`, fill = Day))+
  geom_boxplot(fill = c('#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = 'Open Rate by Day of the Week')+
  geom_text(data = countsMF,
            aes(Day, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

emailsMF %>%
  ggplot(aes(Day, `Open Rate`, fill = Day,))+
  geom_boxplot(fill = c('#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      ,
      axis.text.x = element_text(angle = 90, hjust=1)
    )+
  labs(title = 'Open Rate by Day of the Week Relative to COVID-19')+
  facet_wrap( ~ Covid)+
  geom_text(data = countsMF2,
            aes(Day, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 1), "%")),
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

ggplot(data=emails, mapping=aes(x=`Subject Length`, y=`Open Rate`))+
  geom_point(color = c('#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  geom_smooth(method=lm,se=FALSE, color = '#003a5d')+
  labs(title = 'Open Rate by Subject Length',
       x = 'Subject Length (characters)')

ggplot(data = emails, aes(x = Punctuation, y = `Open Rate`, fill = Punctuation))+
  geom_boxplot(fill = c('#003a5d', '#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = "Open Rate by Presence of Punctuation")+
  geom_text(data = counts2,
            aes(Punctuation, Inf, label = n), vjust = 1) +
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

puncM <- lm(`Open Rate` ~ Punctuation, data=emails)
anovaP <- anova(puncM)
#p = 0.3261859

havePunc %>%
  ggplot(aes(Punc, `Open Rate`, fill = Punc))+
  geom_boxplot(fill = c('#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = "Open Rate by Type of Punctuation",
       x = 'Punctuation')+
  geom_text(data = counts7,
            aes(Punc, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

emailsLC %>%
  ggplot(aes(lastChar, `Open Rate`, fill = lastChar))+
  geom_boxplot(fill=c('#003a5d', '#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  geom_text(data = counts3,
            aes(lastChar, Inf, label = n), vjust = 1)+
  labs(x= 'Last Character',
       y= 'Open Rate',
       title = ' Open Rate by Last Character')+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

modelLC <- lm(`Open Rate` ~ lastChar, emailsLC)
anovaLC <- anova(modelLC)
#p = 2.27148e-06

emailsLC %>%
  ggplot( aes(x=lastChar, y=`Open Rate`, fill=lastChar)) +
    geom_violin(width=1.0) +
    geom_boxplot(width=0.3, color="black", alpha=0.2) +
    scale_fill_viridis(discrete = TRUE) +
    theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  geom_text(data = counts3,
            aes(lastChar, Inf, label = n), vjust = 1) +
  labs(x= 'Last Character',
       y= 'Open Rate',
       title = ' Open Rate by Last Character')+
  scale_fill_manual(values=c('#003a5d', '#0091b3'))+
  stat_summary(fun = median, geom = "crossbar", width = .3, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

both2 %>%
  ggplot(aes(Source, `Open Rate`, fill = Source))+
  geom_boxplot(fill = c('#003a5d', '#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = "Open Rate by Punctuation",
       x = "Punctuation")+
  geom_text(data = countsBoth2,
            aes(Source, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

modelBoth2 <- lm(`Open Rate` ~ Source, both2)
anovaB2 <- anova(modelBoth2)
#p = 0.005394861

emails %>% 
  ggplot(aes(Size, `Open Rate`, fill = Size))+
  geom_boxplot(fill = c('#003a5d', '#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = "Open Rate by Company Size")+
  geom_text(data = countsSize,
            aes(Size, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

sizeM <- lm(`Open Rate` ~ Size, emails)
asizeM <- anova(sizeM)
#p = 0.1473003

emails %>%
  ggplot(aes(Duplicate, `Open Rate`))+
  geom_boxplot(fill = c('#003a5d', '#0091b3'))+
  theme_ipsum(axis_title_size = 12) +
    theme(
      legend.position="none",
      
    )+
  labs(title = "Open Rate by Duplicate Subjects")+
  geom_text(data = countsDup,
            aes(Duplicate, Inf, label = n), vjust = 1)+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  stat_summary(fun = median, geom = "text", aes(label = paste0(round(..y.., 2), "%")), 
               position = position_dodge(width = 0.75), vjust = -0.5, color = "white")

modelD <- lm(`Open Rate` ~ Duplicate, data = emails)
anovaD <- anova(modelD)
#p = 0.7162413

keywords %>%
  ggplot(aes(x = reorder(Keyword, `Open Rate`, FUN = median), y = `Click Rate`))+
  geom_boxplot(fill = c('#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3', '#003a5d', '#0091b3'))+
  geom_text(data = countsKeywords,
            aes(Keyword, Inf, label = n), vjust = 1)+
  theme_ipsum(axis_title_size = 12)+
  theme(axis.text.x = element_text(angle = 90, hjust=1))+
  stat_summary(fun = median, geom = "crossbar", width = .75, color = "#a9ad00", size = .4)+
  labs(title = "Open Rate by Presence of Keywords",
       x = 'Keyword')

modelK <- lm(`Open Rate` ~ Keyword, keywords)
anovaK <- anova(modelK)
#p = 0.0001408233
```
